export default {
    primaryColor: "#4a1482",
    accentColor: "#ff6f00",
    accent: "white",
    title: "#210D3A",
    subtitle: "#6F687A",
    defaultColor: "#b2b2b2",
    backgroundTransparent: "transparent",
    defaultBlue: "#0084ff",
    leftBubbleBackground: "#f0f0f0",
    black: "#000",
    white: "#fff",
    carrot: "#e67e22",
    emerald: "#2ecc71",
    peterRiver: "#3498db",
    wisteria: "#8e44ad",
    alizarin: "#e74c3c",
    turquoise: "#1abc9c",
    midnightBlue: "#2c3e50",
    optionTintColor: "#007AFF",
    timeTextColor: "#aaa",
};
